services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=reas
      - MONGO_INITDB_ROOT_PASSWORD=reas
    networks:
      - reas_network

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8290:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=reas
      - ME_CONFIG_MONGODB_ADMINPASSWORD=reas
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
    networks:
      - reas_network

volumes:
  mongo: {}

networks:
  reas_network:
