services:
  # PgVector
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: reas
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - reas_network
    entrypoint: >
      sh -c "apt update && apt install -y postgis postgresql-16-postgis-3 &&
             docker-entrypoint.sh postgres"

  # MongoDB
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: reas
      MONGO_INITDB_ROOT_PASSWORD: reas
    networks:
      - reas_network

  # Mongo Express for MongoDB Management
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    depends_on:
      - mongo
    ports:
      - "8290:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: reas
      ME_CONFIG_MONGODB_ADMINPASSWORD: reas
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
    networks:
      - reas_network

volumes:
  postgres_data:
  mongo_data:

networks:
  reas_network:
